listening-port=3478
tls-listening-port=5349
fingerprint
use-auth-secret
static-auth-secret=replace-with-turn-rest-secret
realm=youda.example.com
total-quota=200
bps-capacity=0
stale-nonce=600
no-multicast-peers
no-cli
log-file=stdout
simple-log
no-loopback-peers
no-tcp-relay
external-ip=127.0.0.1
